version: "3.8"

services:
  airlines:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airlines-sample-app
    hostname: airlines-sample-app
    ports:
      - "9000:9000"
    env_file:
      - env.list
    